version: '3.8'

services:
  db:
    image: postgres:16.4
    container_name: sense_pro_pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sensepro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user  # Default username
      RABBITMQ_DEFAULT_PASS: password  # Default password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  web:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Dockerfile name (if it's named Dockerfile, you can omit this line)
    container_name: nextjs_app
    restart: always
    environment:
      DATABASE_URL: "postgresql://admin:admin@db:5432/sensepro"
      RABBITMQ_URL: "amqp://user:password@rabbitmq:5672"
      MQ_URL: "amqp://user:password@rabbitmq:5672"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq

volumes:
  rabbitmq_data:
  postgres_data:
    driver: local
