services:
  reverse-proxy:
    image: traefik:v3.2.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=admin@salon.rocks"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "8080:8080" # Traefik panel
      - "443:443" # HTTPS port
    volumes:
      # So that Traefik can listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
  db:
    image: postgres:17.0
    container_name: sense_pro_pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sensepro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "7070:8080"
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user  # Default username
      RABBITMQ_DEFAULT_PASS: password  # Default password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  sensepro:
    image: ghcr.io/moreorover/sensepro-admin-panel:latest
#    build:
#      context: .  # Path to the directory containing the Dockerfile
#      dockerfile: Dockerfile  # Dockerfile name (if it's named Dockerfile, you can omit this line)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sensepro.rule=Host(`salon.rocks`)"
      - "traefik.http.routers.sensepro.entrypoints=websecure"
      - "traefik.http.routers.sensepro.tls.certresolver=myresolver"
    restart: always
    environment:
      DATABASE_URL: "postgresql://admin:admin@db:5432/sensepro"
      RABBITMQ_URL: "amqp://user:password@rabbitmq:5672"
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - db
      - rabbitmq

volumes:
  letsencrypt:
  rabbitmq_data:
  postgres_data:
    driver: local
