name: Build and Push Docker Image on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (optional but recommended for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/SensePro-admin-panel:$TAG .
          docker tag ghcr.io/${{ github.repository_owner }}/SensePro-admin-panel:$TAG ghcr.io/${{ github.repository_owner }}/SensePro-admin-panel:latest

      # Push the Docker image
      - name: Push Docker image
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/SensePro-admin-panel:$TAG
          docker push ghcr.io/${{ github.repository_owner }}/SensePro-admin-panel:latest
