name: Release and Build Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  release-it:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Configure Git user information
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx release-it

  build-and-push:
    needs: release-it
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/SensePro-admin-panel:$TAG .
          docker tag ghcr.io/${{ github.repository_owner }}/SensePro-admin-panel:$TAG ghcr.io/${{ github.repository_owner }}/SensePro-admin-panel:latest

      - name: Push Docker image
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/SensePro-admin-panel:$TAG
          docker push ghcr.io/${{ github.repository_owner }}/SensePro-admin-panel:latest
